export default {
  menu_category_off: require('./asset/menu_category.png'),
  menu_category_on: require('./asset/menu_category.png'),
  menu_lesson_off: require('./asset/menu_lesson.png'),
  menu_lesson_on: require('./asset/menu_lesson.png'),
  menu_challenge_off: require('./asset/menu_challenge.png'),
  menu_challenge_on: require('./asset/menu_challenge.png'),
  menu_contents_off: require('./asset/menu_contents.png'),
  menu_contents_on: require('./asset/menu_contents.png'),
  menu_home_off: require('./asset/menu_home.png'),
  menu_home_on: require('./asset/menu_home.png'),
  menu_mypage_off: require('./asset/menu_mypage.png'),
  menu_mypage_on: require('./asset/menu_mypage.png'),
  menu_notice_off: require('./asset/menu_notice.png'),
  menu_notice_on: require('./asset/menu_notice.png'),
  header_back: require('./asset/header_back.png'),
  header_back_dk: require('./asset/header_back_dk.png'),
  btn_close_black: require('./asset/btn_close_black.png'),
};
